Feature: AI-Driven Health Insights
  As a user
  I want to receive AI-generated insights based on my recent fitness and recovery data
  So that I can get personalized recommendations and identify meaningful trends in my health

  Scenario: Generating insights successfully
    Given I have successfully synced recent data from Strava and Whoop
    And the system is configured with a valid Google Gemini API key
    When I navigate to the Dashboard page
    Then the system sends my 15 most recent Strava activities and Whoop cycles to the Gemini AI model
    And the system prompts the AI to act as a health and fitness coach analyzing trends
    And the Dashboard page displays 3-4 paragraphs of insights generated by the AI

  Scenario: Attempting to generate insights without an API key
    Given the system is not configured with a Google Gemini API key
    When I navigate to the Dashboard page
    Then the system bypasses the AI generation process
    And the Dashboard page displays a message indicating that the Gemini API key is missing

  Scenario: Attempting to generate insights with insufficient data
    Given the local database contains no recent Strava or Whoop data
    When I navigate to the Dashboard page
    Then the system skips sending data to the Gemini AI model
    And the Dashboard page displays a message indicating there is not enough data to generate insights
